import {
  AlarmClockCheck,
  Armchair,
  ArrowLeft,
  ArrowRight,
  BookOpenText,
  BarChart3,
  BellRing,
  Bot,
  Brain,
  BriefcaseBusiness,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  CameraOff,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  Clock3,
  ClipboardList,
  Dumbbell,
  FileVideo,
  FilePenLine,
  Flag,
  FlipHorizontal,
  GraduationCap,
  Group,
  Heart,
  History,
  Image,
  Landmark,
  LayoutGrid,
  Lightbulb,
  Link2Off,
  ListChecks,
  Lock,
  Mail,
  MessageCircle,
  Moon,
  MoonStar,
  Pencil,
  Plus,
  RefreshCw,
  RotateCcw,
  Send,
  Share2,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Sunrise,
  Target,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  Utensils,
  Video,
  VideoOff,
  X,
  type LucideIcon,
} from 'lucide-react';

interface MaterialIconProps {
  icon: string;
  size?: number;
  color?: string;
  filled?: boolean;
  className?: string;
  style?: React.CSSProperties;
}

const ICONS: Record<string, LucideIcon> = {
  account_balance: Landmark,
  add: Plus,
  add_photo_alternate: Image,
  alarm_on: AlarmClockCheck,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  bar_chart: BarChart3,
  bedtime: Moon,
  calendar_month: CalendarDays,
  check: Check,
  check_circle: CircleCheck,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  content_copy: Share2,
  dark_mode: Moon,
  delete: Trash2,
  chat: MessageCircle,
  assignment: ClipboardList,
  directions_run: Dumbbell,
  edit: Pencil,
  edit_calendar: CalendarClock,
  edit_note: FilePenLine,
  event: CalendarClock,
  event_available: CalendarCheck,
  flip_camera_ios: FlipHorizontal,
  light_mode: Sun,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  flag: Flag,
  free_cancellation: Clock3,
  group: Group,
  group_add: UserPlus,
  history: History,
  image: Image,
  insights: BarChart3,
  link_off: Link2Off,
  lock: Lock,
  lunch_dining: Utensils,
  mail: Mail,
  menu_book: GraduationCap,
  nights_stay: MoonStar,
  nightlife: MoonStar,
  notifications: BellRing,
  notifications_active: BellRing,
  pending: Clock3,
  person: User,
  photo_camera: Camera,
  psychology: Brain,
  quiz: GraduationCap,
  radio_button_unchecked: Circle,
  refresh: RotateCcw,
  schedule: CalendarDays,
  school: GraduationCap,
  send: Send,
  share: Share2,
  smart_toy: Bot,
  thumb_up: ThumbsUp,
  today: CalendarDays,
  tips_and_updates: Lightbulb,
  track_changes: Target,
  tune: SlidersHorizontal,
  update: History,
  upload_file: Upload,
  videocam: Video,
  videocam_off: VideoOff,
  video_camera_back: CameraOff,
  view_week: BookOpenText,
  warning: TriangleAlert,
  wb_sunny: Sun,
  wb_twilight: Sunrise,
  weekend: Armchair,
  widgets: LayoutGrid,
  work: BriefcaseBusiness,
};

export default function MaterialIcon({ icon, size = 24, color, filled = false, className = '', style }: MaterialIconProps) {
  const Icon = ICONS[icon] ?? Circle;

  return (
    <Icon
      aria-hidden="true"
      className={className}
      style={{
        color,
        display: 'inline-block',
        flexShrink: 0,
        verticalAlign: '-0.15em',
        ...style,
      }}
      width={size}
      height={size}
      strokeWidth={filled ? 2.35 : 2}
    />
  );
}
